/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness */
        get: operations["liveness_api_v1_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness */
        get: operations["readiness_api_v1_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/suppliers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Suppliers */
        get: operations["list_suppliers_api_v1_catalog_suppliers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/materials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Materials */
        get: operations["list_materials_api_v1_catalog_materials_get"];
        put?: never;
        /** Create Material */
        post: operations["create_material_api_v1_catalog_materials_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Locations */
        get: operations["list_locations_api_v1_catalog_locations_get"];
        put?: never;
        /** Create Location */
        post: operations["create_location_api_v1_catalog_locations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/supplier-materials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Supplier Materials */
        get: operations["list_supplier_materials_api_v1_catalog_supplier_materials_get"];
        put?: never;
        /** Create Supplier Material */
        post: operations["create_supplier_material_api_v1_catalog_supplier_materials_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/reason-codes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Reason Codes */
        get: operations["list_reason_codes_api_v1_catalog_reason_codes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory/receipts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Receive Pallet */
        post: operations["receive_pallet_api_v1_inventory_receipts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory/pallets/{pallet_id}/issues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Issue Stock */
        post: operations["issue_stock_api_v1_inventory_pallets__pallet_id__issues_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory/pallets/{pallet_id}/blocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Block Stock */
        post: operations["block_stock_api_v1_inventory_pallets__pallet_id__blocks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory/pallets/{pallet_id}/unblocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unblock Stock */
        post: operations["unblock_stock_api_v1_inventory_pallets__pallet_id__unblocks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory/pallets/{pallet_id}/discards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Discard Stock */
        post: operations["discard_stock_api_v1_inventory_pallets__pallet_id__discards_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory/pallets/{pallet_id}/returns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Return Stock */
        post: operations["return_stock_api_v1_inventory_pallets__pallet_id__returns_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory/pallets/{pallet_id}/transfers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transfer Pallet */
        post: operations["transfer_pallet_api_v1_inventory_pallets__pallet_id__transfers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory/movements/{movement_id}/reversal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reverse Movement */
        post: operations["reverse_movement_api_v1_inventory_movements__movement_id__reversal_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory/stock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Stock */
        get: operations["list_stock_api_v1_inventory_stock_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory/pallets/{pallet_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Pallet */
        get: operations["get_pallet_api_v1_inventory_pallets__pallet_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory/pallets/{pallet_id}/movements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Movements */
        get: operations["list_movements_api_v1_inventory_pallets__pallet_id__movements_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory/materials/{material_id}/rotation-recommendation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rotation Recommendation */
        get: operations["rotation_recommendation_api_v1_inventory_materials__material_id__rotation_recommendation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** DiscardCommand */
        DiscardCommand: {
            /** Quantity Sheets */
            quantity_sheets: number;
            /** Reason Code */
            reason_code: string;
            /** Notes */
            notes?: string | null;
            /** Destination Reference */
            destination_reference?: string | null;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at?: string;
            /**
             * Source Bucket
             * @enum {string}
             */
            source_bucket: "AVAILABLE" | "BLOCKED";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /** IssueCommand */
        IssueCommand: {
            /** Quantity Sheets */
            quantity_sheets: number;
            /** Reason Code */
            reason_code?: string | null;
            /** Notes */
            notes?: string | null;
            /** Destination Reference */
            destination_reference: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at?: string;
        };
        /** LocationCreate */
        LocationCreate: {
            /** Code */
            code: string;
            /** Name */
            name: string;
        };
        /** LocationResponse */
        LocationResponse: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** MaterialCreate */
        MaterialCreate: {
            /** Internal Code */
            internal_code: string;
            /** Name */
            name: string;
            /** Width Mm */
            width_mm: number;
            /** Length Mm */
            length_mm: number;
            /** @default FIFO */
            rotation_policy: components["schemas"]["RotationPolicy"];
        };
        /** MaterialResponse */
        MaterialResponse: {
            /** Internal Code */
            internal_code: string;
            /** Name */
            name: string;
            /** Width Mm */
            width_mm: number;
            /** Length Mm */
            length_mm: number;
            /** @default FIFO */
            rotation_policy: components["schemas"]["RotationPolicy"];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** MovementResponse */
        MovementResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Pallet Id
             * Format: uuid
             */
            pallet_id: string;
            /** Movement Type */
            movement_type: string;
            /** From Bucket */
            from_bucket: string | null;
            /** To Bucket */
            to_bucket: string | null;
            /** Quantity */
            quantity: number | null;
            /** From Location Id */
            from_location_id: string | null;
            /** To Location Id */
            to_location_id: string | null;
            /** Source Movement Id */
            source_movement_id: string | null;
            /** Reason Code */
            reason_code: string | null;
            /** Notes */
            notes: string | null;
            /** Destination Reference */
            destination_reference: string | null;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Created By
             * Format: uuid
             */
            created_by: string;
        };
        /** PalletResponse */
        PalletResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Internal Code */
            internal_code: string;
            /** Internal Qr */
            internal_qr: string;
            /**
             * Supplier Id
             * Format: uuid
             */
            supplier_id: string;
            /**
             * Material Id
             * Format: uuid
             */
            material_id: string;
            /**
             * Location Id
             * Format: uuid
             */
            location_id: string;
            /** Supplier Material Name */
            supplier_material_name: string;
            /** Supplier Pallet Code */
            supplier_pallet_code: string | null;
            /** Supplier Sscc */
            supplier_sscc: string | null;
            /** Lot Code */
            lot_code: string | null;
            /** Received Quantity */
            received_quantity: number;
            /** Available Quantity */
            available_quantity: number;
            /** Blocked Quantity */
            blocked_quantity: number;
            /** Consumed Quantity */
            consumed_quantity: number;
            /** Discarded Quantity */
            discarded_quantity: number;
            /** Width Mm */
            width_mm: number;
            /** Length Mm */
            length_mm: number;
            /** Declared Area M2 */
            declared_area_m2: string | null;
            /** Manufactured At */
            manufactured_at: string | null;
            /** Expires On */
            expires_on: string | null;
            /** Orientation */
            orientation: string | null;
            /** Lifecycle Status */
            lifecycle_status: string;
            /** Version */
            version: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ReasonCodeResponse */
        ReasonCodeResponse: {
            /** Code */
            code: string;
            /** Category */
            category: string;
            /** Label */
            label: string;
            /** Is Active */
            is_active: boolean;
        };
        /** ReceiptCommand */
        ReceiptCommand: {
            /**
             * Supplier Id
             * Format: uuid
             */
            supplier_id: string;
            /**
             * Material Id
             * Format: uuid
             */
            material_id: string;
            /**
             * Location Id
             * Format: uuid
             */
            location_id: string;
            /** Supplier Material Name */
            supplier_material_name: string;
            /** Supplier Pallet Code */
            supplier_pallet_code?: string | null;
            /** Supplier Sscc */
            supplier_sscc?: string | null;
            /** Lot Code */
            lot_code?: string | null;
            /** Quantity Sheets */
            quantity_sheets: number;
            /** Width Mm */
            width_mm: number;
            /** Length Mm */
            length_mm: number;
            /** Declared Area M2 */
            declared_area_m2?: number | string | null;
            /** Manufactured At */
            manufactured_at?: string | null;
            /** Expires On */
            expires_on?: string | null;
            /** Orientation */
            orientation?: string | null;
            /** Raw Label Payload */
            raw_label_payload?: {
                [key: string]: unknown;
            } | null;
            /** Label Scan Id */
            label_scan_id?: string | null;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at?: string;
        };
        /** RequiredReasonMovementCommand */
        RequiredReasonMovementCommand: {
            /** Quantity Sheets */
            quantity_sheets: number;
            /** Reason Code */
            reason_code: string;
            /** Notes */
            notes?: string | null;
            /** Destination Reference */
            destination_reference?: string | null;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at?: string;
        };
        /** ReversalCommand */
        ReversalCommand: {
            /** Reason Code */
            reason_code: string;
            /** Notes */
            notes: string;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at?: string;
        };
        /**
         * RotationPolicy
         * @enum {string}
         */
        RotationPolicy: "FIFO" | "FEFO";
        /** RotationRecommendationResponse */
        RotationRecommendationResponse: {
            /**
             * Material Id
             * Format: uuid
             */
            material_id: string;
            recommended_pallet: components["schemas"]["PalletResponse"] | null;
        };
        /** SupplierMaterialCreate */
        SupplierMaterialCreate: {
            /**
             * Supplier Id
             * Format: uuid
             */
            supplier_id: string;
            /**
             * Material Id
             * Format: uuid
             */
            material_id: string;
            /** Supplier Code */
            supplier_code?: string | null;
            /** Supplier Name */
            supplier_name: string;
        };
        /** SupplierMaterialResponse */
        SupplierMaterialResponse: {
            /**
             * Supplier Id
             * Format: uuid
             */
            supplier_id: string;
            /**
             * Material Id
             * Format: uuid
             */
            material_id: string;
            /** Supplier Code */
            supplier_code?: string | null;
            /** Supplier Name */
            supplier_name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** SupplierResponse */
        SupplierResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Is Active */
            is_active: boolean;
        };
        /** TransferCommand */
        TransferCommand: {
            /**
             * To Location Id
             * Format: uuid
             */
            to_location_id: string;
            /** Reason Code */
            reason_code?: string | null;
            /** Notes */
            notes?: string | null;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at?: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    liveness_api_v1_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    readiness_api_v1_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_suppliers_api_v1_catalog_suppliers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplierResponse"][];
                };
            };
        };
    };
    list_materials_api_v1_catalog_materials_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialResponse"][];
                };
            };
        };
    };
    create_material_api_v1_catalog_materials_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MaterialCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_locations_api_v1_catalog_locations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationResponse"][];
                };
            };
        };
    };
    create_location_api_v1_catalog_locations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_supplier_materials_api_v1_catalog_supplier_materials_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplierMaterialResponse"][];
                };
            };
        };
    };
    create_supplier_material_api_v1_catalog_supplier_materials_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SupplierMaterialCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplierMaterialResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_reason_codes_api_v1_catalog_reason_codes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReasonCodeResponse"][];
                };
            };
        };
    };
    receive_pallet_api_v1_inventory_receipts_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReceiptCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PalletResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    issue_stock_api_v1_inventory_pallets__pallet_id__issues_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                pallet_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IssueCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovementResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    block_stock_api_v1_inventory_pallets__pallet_id__blocks_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                pallet_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequiredReasonMovementCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovementResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unblock_stock_api_v1_inventory_pallets__pallet_id__unblocks_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                pallet_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequiredReasonMovementCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovementResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    discard_stock_api_v1_inventory_pallets__pallet_id__discards_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                pallet_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiscardCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovementResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    return_stock_api_v1_inventory_pallets__pallet_id__returns_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                pallet_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequiredReasonMovementCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovementResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    transfer_pallet_api_v1_inventory_pallets__pallet_id__transfers_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                pallet_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransferCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovementResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reverse_movement_api_v1_inventory_movements__movement_id__reversal_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                movement_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReversalCommand"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovementResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_stock_api_v1_inventory_stock_get: {
        parameters: {
            query?: {
                supplier_id?: string | null;
                material_id?: string | null;
                location_id?: string | null;
                include_depleted?: boolean;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PalletResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pallet_api_v1_inventory_pallets__pallet_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pallet_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PalletResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_movements_api_v1_inventory_pallets__pallet_id__movements_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pallet_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovementResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rotation_recommendation_api_v1_inventory_materials__material_id__rotation_recommendation_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                material_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RotationRecommendationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
